server:
  port: 9090

spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/ecommerce?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLocalSessionState=true
    username: root
    password: fighting

jwt:
  issuer: jara
  subject: auth
  expires-time: 3600
  version: 1.0.0
  secret: secret
  refresh: refresh
  refresh-expires-time: 36000
